# Generated by Django 5.2 on 2025-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_content', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
